=== SaifAqqad/AHK_MicMute/src/config/config_schema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$ref": "#/definitions/Config",
    "definitions": {
        "Config": {
            "type": "object",
            "additionalProperties": true,
            "properties": {
                "DefaultProfile": {
                    "type": "string"
                },
                "MuteOnStartup": {
                    "type": ["integer","boolean"]
                },
                "Profiles": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Profile"
                    }
                },
                "SwitchProfileOSD": {
                    "type": ["integer","boolean"]
                },
                "UseCustomSounds": {
                    "type": ["integer","boolean"]
                }
            },
            "required": [
                "DefaultProfile",
                "Profiles"
            ],
            "title": "Config"
        },
        "Profile": {
            "type": "object",
            "additionalProperties": true,
            "properties": {
                "afkTimeout": {
                    "type": "number"
                },
                "ExcludeFullscreen": {
                    "type": ["integer","boolean"]
                },
                "LinkedApp": {
                    "type": "string"
                },
                "Microphone": {
                    "type": "string"
                },
                "MuteHotkey": {
                    "type": "string"
                },
                "OnscreenFeedback": {
                    "type": ["integer","boolean"]
                },
                "OSDPos": {
                    "$ref": "#/definitions/OSDPos"
                },
                "ProfileName": {
                    "type": "string"
                },
                "PushToTalk": {
                    "type": ["integer","boolean"]
                },
                "PTTDelay": {
                    "type": "number"
                },
                "SoundFeedback": {
                    "type": ["integer","boolean"]
                },
                "UnmuteHotkey": {
                    "type": "string"
                },
                "UpdateWithSystem": {
                    "type": ["integer","boolean"]
                }
            },
            "required": [
                "Microphone",
                "MuteHotkey",
                "ProfileName",
                "PushToTalk",
                "UnmuteHotkey"
            ],
            "title": "Profile"
        },
        "OSDPos": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "x": {
                    "type": "integer"
                },
                "y": {
                    "type": "integer"
                }
            },
            "required": [
                "x",
                "y"
            ],
            "title": "OSDPos"
        }
    }
}

=== SaifAqqad/AHK_MicMute/src/config/old_config.json
{
    "DefaultProfile": "Default",
    "MuteOnStartup": 0,
    "Profiles": [
        {
            "afkTimeout": 0,
            "ExcludeFullscreen": 0,
            "LinkedApp": "",
            "Microphone": "Microphone (AmazonBasics Desktop Mini Mic)",
            "MuteHotkey": "~*RShift",
            "OnscreenFeedback": 1,
            "OSDPos": {
                "x": -1,
                "y": -1
            },
            "ProfileName": "Default",
            "PTTDelay": 100,
            "PushToTalk": 0,
            "SoundFeedback": 1,
            "UnmuteHotkey": "~*RShift",
            "UpdateWithSystem": 1
        },
        {
            "afkTimeout": 0,
            "ExcludeFullscreen": 0,
            "LinkedApp": "firefox.exe",
            "Microphone": "Microphone (AmazonBasics Desktop Mini Mic)",
            "MuteHotkey": "~*RShift",
            "OnscreenFeedback": 1,
            "OSDPos": {
                "x": 145,
                "y": 1000
            },
            "ProfileName": "Firefox",
            "PTTDelay": 100,
            "PushToTalk": 1,
            "SoundFeedback": 1,
            "UnmuteHotkey": "~*RShift",
            "UpdateWithSystem": 1
        }
    ],
    "SwitchProfileOSD": 1,
    "UseCustomSounds": 0
}
