=== SaifAqqad/AHK_MicMute/src/config/schema.json
{
    "definitions": {},
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Config",
    "type": "object",
    "required": [
        "DefaultProfile",
        "Profiles"
    ],
    "properties": {
        "DefaultProfile": {
            "$id": "#root/DefaultProfile",
            "title": "Defaultprofile",
            "type": "string",
            "default": "",
            "examples": [
                "Default"
            ],
            "pattern": "^.*$"
        },
        "MuteOnStartup": {
            "$id": "#root/MuteOnStartup",
            "title": "Muteonstartup",
            "type": [
                "integer",
                "boolean"
            ],
            "examples": [
                0
            ],
            "default": 0
        },
        "PreferTheme": {
            "$id": "#root/PreferTheme",
            "title": "Prefertheme",
            "type": "integer",
            "examples": [
                0
            ],
            "default": -1
        },
        "Profiles": {
            "$id": "#root/Profiles",
            "title": "Profiles",
            "type": "array",
            "default": [],
            "items": {
                "$id": "#root/Profiles/items",
                "title": "Profile",
                "type": "object",
                "required": [
                    "Microphone",
                    "ProfileName"
                ],
                "properties": {
                    "afkTimeout": {
                        "$id": "#root/Profiles/items/afkTimeout",
                        "title": "Afktimeout",
                        "type": "integer",
                        "examples": [
                            0
                        ],
                        "default": 0
                    },
                    "ExcludeFullscreen": {
                        "$id": "#root/Profiles/items/ExcludeFullscreen",
                        "title": "Excludefullscreen",
                        "type": [
                            "integer",
                            "boolean"
                        ],
                        "examples": [
                            1
                        ],
                        "default": 0
                    },
                    "LinkedApp": {
                        "$id": "#root/Profiles/items/LinkedApp",
                        "title": "Linkedapp",
                        "type": "string",
                        "default": "",
                        "examples": [
                            "example.exe"
                        ],
                        "pattern": "^.*\\.exe$"
                    },
                    "Microphone": {
                        "$id": "#root/Profiles/items/Microphone",
                        "title": "Microphone",
                        "type": "array",
                        "default": [],
                        "items": {
                            "$id": "#root/Profiles/items/Microphone/items",
                            "title": "Microphone Object",
                            "type": "object",
                            "required": [
                                "MuteHotkey",
                                "Name",
                                "PushToTalk",
                                "UnmuteHotkey"
                            ],
                            "properties": {
                                "MuteHotkey": {
                                    "$id": "#root/Profiles/items/Microphone/items/MuteHotkey",
                                    "title": "Mutehotkey",
                                    "type": "string",
                                    "default": "",
                                    "examples": [
                                        "~*<^R"
                                    ]
                                },
                                "Name": {
                                    "$id": "#root/Profiles/items/Microphone/items/Name",
                                    "title": "Name",
                                    "type": "string",
                                    "default": "",
                                    "examples": [
                                        "Microphone (Desktop Mini Mic)"
                                    ]
                                },
                                "PushToTalk": {
                                    "$id": "#root/Profiles/items/Microphone/items/PushToTalk",
                                    "title": "Pushtotalk",
                                    "type": [
                                        "integer",
                                        "boolean"
                                    ],
                                    "examples": [
                                        1
                                    ],
                                    "default": 0
                                },
                                "UnmuteHotkey": {
                                    "$id": "#root/Profiles/items/Microphone/items/UnmuteHotkey",
                                    "title": "Unmutehotkey",
                                    "type": "string",
                                    "default": "",
                                    "examples": [
                                        "~*<^R"
                                    ]
                                }
                            }
                        }
                    },
                    "OnscreenFeedback": {
                        "$id": "#root/Profiles/items/OnscreenFeedback",
                        "title": "Onscreenfeedback",
                        "type": [
                            "integer",
                            "boolean"
                        ],
                        "examples": [
                            1
                        ],
                        "default": 0
                    },
                    "OSDPos": {
                        "$id": "#root/Profiles/items/OSDPos",
                        "title": "OSD position",
                        "type": "object",
                        "required": [
                            "x",
                            "y"
                        ],
                        "properties": {
                            "x": {
                                "$id": "#root/Profiles/items/OSDPos/x",
                                "title": "X coordinate",
                                "type": "integer",
                                "examples": [
                                    150
                                ],
                                "default": -1
                            },
                            "y": {
                                "$id": "#root/Profiles/items/OSDPos/y",
                                "title": "Y coordinate",
                                "type": "integer",
                                "examples": [
                                    340
                                ],
                                "default": -1
                            }
                        }
                    },
                    "ProfileName": {
                        "$id": "#root/Profiles/items/ProfileName",
                        "title": "Profile name",
                        "type": "string",
                        "default": "",
                        "examples": [
                            "Default"
                        ]
                    },
                    "PTTDelay": {
                        "$id": "#root/Profiles/items/PTTDelay",
                        "title": "Pttdelay",
                        "type": "integer",
                        "examples": [
                            100
                        ],
                        "default": 100
                    },
                    "SoundFeedback": {
                        "$id": "#root/Profiles/items/SoundFeedback",
                        "title": "Soundfeedback",
                        "type": [
                            "integer",
                            "boolean"
                        ],
                        "examples": [
                            1
                        ],
                        "default": 0
                    },
                    "UpdateWithSystem": {
                        "$id": "#root/Profiles/items/UpdateWithSystem",
                        "title": "Updatewithsystem",
                        "type": [
                            "integer",
                            "boolean"
                        ],
                        "examples": [
                            1
                        ],
                        "default": 1
                    }
                }
            }
        },
        "SwitchProfileOSD": {
            "$id": "#root/SwitchProfileOSD",
            "title": "Switching-profile OSD",
            "type": ["integer","boolean"],
            "examples": [
                1
            ],
            "default": 1
        },
        "UseCustomSounds": {
            "$id": "#root/UseCustomSounds",
            "title": "Usecustomsounds",
            "type": ["integer","boolean"],
            "examples": [
                0
            ],
            "default": 0
        }
    }
}

=== SaifAqqad/AHK_MicMute/src/config/config.json
{
    "DefaultProfile": "Default",
    "MuteOnStartup": 0,
    "PreferTheme": -1,
    "Profiles": [
        {
            "afkTimeout": 0,
            "ExcludeFullscreen": 0,
            "LinkedApp": "",
            "Microphone": [
                {
                    "MuteHotkey": "~*<^R",
                    "Name": "AmazonBasics (AmazonBasics Desktop Mini Mic)",
                    "PushToTalk": 0,
                    "UnmuteHotkey": "~*<^R"
                }
            ],
            "OnscreenFeedback": 1,
            "OSDPos": {
                "x": -1,
                "y": -1
            },
            "ProfileName": "Default",
            "PTTDelay": 100,
            "SoundFeedback": 1,
            "UpdateWithSystem": 1
        },
        {
            "afkTimeout": 0,
            "ExcludeFullscreen": 1,
            "LinkedApp": "firefox.exe",
            "Microphone": [
                {
                    "MuteHotkey": "*^F",
                    "Name": "Default",
                    "PushToTalk": 0,
                    "UnmuteHotkey": "*^F"
                },
                {
                    "MuteHotkey": "^D",
                    "Name": "VoiceMeeter Output (VB-Audio VoiceMeeter VAIO)",
                    "PushToTalk": 0,
                    "UnmuteHotkey": "^D"
                }
            ],
            "OnscreenFeedback": 1,
            "OSDPos": {
                "x": 145,
                "y": 1000
            },
            "ProfileName": "Firefox",
            "PTTDelay": 50,
            "SoundFeedback": 1,
            "UpdateWithSystem": 1
        }
    ],
    "SwitchProfileOSD": 1,
    "UseCustomSounds": 0
}
